[build]
    publish = "dist/client"
    command = "npm run build"

[functions]
    directory = "netlify/functions/"
    included_files = ["dist/client/.vite/manifest.json"]

[dev]
    publish = "dist/client"
    command = "npm run dev"
    
